[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.arc-testnet]
rpc_url = "${ARC_TESTNET_RPC_URL}"
private_key = "${PRIVATE_KEY}"

